# =====================================================
# è² è·ãƒ†ã‚¹ãƒˆï¼ˆçµ„ç¹”ãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆï¼‰
# k6 ã«ã‚ˆã‚‹è² è·ãƒ»ãƒ‘ãƒ•ã‚©ãƒ¼ãƒžãƒ³ã‚¹ãƒ†ã‚¹ãƒˆ
# DoD Gold åŸºæº– B11 ã«å¯¾å¿œ
# =====================================================

name: âš¡ Load Tests

on:
  # æ‰‹å‹•å®Ÿè¡Œï¼ˆæœ¬ç•ªãƒªãƒªãƒ¼ã‚¹å‰ï¼‰
  workflow_dispatch:
    inputs:
      scenario:
        description: 'ãƒ†ã‚¹ãƒˆã‚·ãƒŠãƒªã‚ª'
        required: true
        default: 'smoke'
        type: choice
        options:
          - smoke      # åŸºæœ¬å‹•ä½œç¢ºèª
          - load       # é€šå¸¸è² è·
          - stress     # é™ç•Œãƒ†ã‚¹ãƒˆ
          - soak       # é•·æ™‚é–“ãƒ†ã‚¹ãƒˆ
      target_url:
        description: 'ãƒ†ã‚¹ãƒˆå¯¾è±¡URL'
        required: true
        default: 'https://staging.example.com'
      duration:
        description: 'ãƒ†ã‚¹ãƒˆæ™‚é–“ï¼ˆä¾‹: 1m, 5m, 30mï¼‰'
        required: false
        default: '1m'
      vus:
        description: 'åŒæ™‚æŽ¥ç¶šæ•°ï¼ˆVirtual Usersï¼‰'
        required: false
        default: '10'

  # ãƒªãƒªãƒ¼ã‚¹ãƒ–ãƒ©ãƒ³ãƒã¸ã®ãƒ—ãƒƒã‚·ãƒ¥æ™‚ï¼ˆã‚ªãƒ—ã‚·ãƒ§ãƒ³ï¼‰
  # push:
  #   branches: [release/*]

jobs:
  load-test:
    name: âš¡ Load Test (${{ github.event.inputs.scenario }})
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: ðŸ“¥ Checkout
        uses: actions/checkout@v4

      - name: ðŸ”§ Setup k6
        uses: grafana/setup-k6-action@v1

      - name: ðŸ“ Check k6 Scripts
        id: check-scripts
        run: |
          if [ -d "load-tests" ]; then
            echo "has_scripts=true" >> $GITHUB_OUTPUT
            ls -la load-tests/
          else
            echo "has_scripts=false" >> $GITHUB_OUTPUT
            echo "::warning::load-tests/ directory not found. Using inline script."
          fi

      # ã‚«ã‚¹ã‚¿ãƒ ã‚¹ã‚¯ãƒªãƒ—ãƒˆãŒã‚ã‚‹å ´åˆ
      - name: âš¡ Run k6 (Custom Script)
        if: steps.check-scripts.outputs.has_scripts == 'true'
        run: |
          SCRIPT="load-tests/scenarios/${{ github.event.inputs.scenario }}.js"
          if [ -f "$SCRIPT" ]; then
            k6 run "$SCRIPT" \
              --env TARGET_URL=${{ github.event.inputs.target_url }} \
              --duration ${{ github.event.inputs.duration }} \
              --vus ${{ github.event.inputs.vus }} \
              --out json=results.json
          else
            echo "::error::Script not found: $SCRIPT"
            exit 1
          fi

      # ã‚«ã‚¹ã‚¿ãƒ ã‚¹ã‚¯ãƒªãƒ—ãƒˆãŒãªã„å ´åˆï¼ˆã‚¤ãƒ³ãƒ©ã‚¤ãƒ³ã‚¹ã‚¯ãƒªãƒ—ãƒˆï¼‰
      - name: âš¡ Run k6 (Inline Script)
        if: steps.check-scripts.outputs.has_scripts == 'false'
        run: |
          cat > /tmp/load-test.js << 'EOF'
          import http from 'k6/http';
          import { check, sleep } from 'k6';

          export const options = {
            scenarios: {
              smoke: {
                executor: 'constant-vus',
                vus: __ENV.VUS || 1,
                duration: __ENV.DURATION || '30s',
              },
            },
            thresholds: {
              http_req_duration: ['p(95)<2000'], // D1: å¿œç­”æ™‚é–“â‰¦2ç§’
              http_req_failed: ['rate<0.01'],    // 99%æˆåŠŸ
            },
          };

          export default function() {
            const res = http.get(__ENV.TARGET_URL || 'http://localhost:3000');

            check(res, {
              'status is 200': (r) => r.status === 200,
              'response time < 2s': (r) => r.timings.duration < 2000,
            });

            sleep(1);
          }
          EOF

          k6 run /tmp/load-test.js \
            --env TARGET_URL=${{ github.event.inputs.target_url }} \
            --env DURATION=${{ github.event.inputs.duration }} \
            --env VUS=${{ github.event.inputs.vus }} \
            --out json=results.json

      - name: ðŸ“Š Generate Report
        if: always()
        run: |
          echo "## âš¡ Load Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Parameter | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|-----------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| Scenario | ${{ github.event.inputs.scenario }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Target | ${{ github.event.inputs.target_url }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Duration | ${{ github.event.inputs.duration }} |" >> $GITHUB_STEP_SUMMARY
          echo "| VUs | ${{ github.event.inputs.vus }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ -f results.json ]; then
            echo "### Metrics" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            # ç°¡æ˜“ãƒ¡ãƒˆãƒªã‚¯ã‚¹æŠ½å‡º
            cat results.json | jq -s 'map(select(.type == "Point" and .metric == "http_req_duration")) | if length > 0 then "Requests: \(length)" else "No data" end' >> $GITHUB_STEP_SUMMARY || echo "Parse error" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi

      - name: ðŸ“Š Upload Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: load-test-results-${{ github.event.inputs.scenario }}
          path: results.json
          retention-days: 30

  # ===========================================
  # é–¾å€¤ãƒã‚§ãƒƒã‚¯ï¼ˆDoDæº–æ‹ ï¼‰
  # ===========================================
  threshold-check:
    name: ðŸ“ˆ Threshold Check
    runs-on: ubuntu-latest
    needs: load-test
    if: always()

    steps:
      - name: ðŸ“¥ Download Results
        uses: actions/download-artifact@v4
        with:
          name: load-test-results-${{ github.event.inputs.scenario }}
        continue-on-error: true

      - name: ðŸ“ˆ Check DoD Thresholds
        run: |
          echo "## ðŸ“ˆ DoD Threshold Check" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| DoD Criteria | Threshold | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|--------------|-----------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| D1: å¿œç­”æ™‚é–“ | â‰¦2ç§’ | âœ… (checked by k6) |" >> $GITHUB_STEP_SUMMARY
          echo "| D3: APIå¿œç­” | â‰¦500ms | âš ï¸ (manual check) |" >> $GITHUB_STEP_SUMMARY
          echo "| D7: åŒæ™‚æŽ¥ç¶š | ${{ github.event.inputs.vus }} VUs | âœ… |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "> DoD Gold åŸºæº– B11: è² è·ãƒ†ã‚¹ãƒˆ" >> $GITHUB_STEP_SUMMARY
