# =====================================================
# PR Governance (Reusable版)
# 組織の Reusable Workflow を呼び出す薄いラッパー
# =====================================================

name: PR Governance

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  governance:
    uses: PROLE-ISLAND/.github/.github/workflows/reusable-pr-governance.yml@main
    with:
      language: 'ja'
      require_why_section: true
      require_issue_branch: true
      enable_auto_labeler: true
      enable_change_summary: true
      enable_variant_check: true
      size_thresholds: '{"small": 100, "large": 500}'
