# =====================================================
# Quality Gate (Reusable版)
# 組織の Reusable Workflow を呼び出す薄いラッパー
# =====================================================

name: Quality Gate

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

permissions:
  pull-requests: write
  statuses: write
  checks: write
  actions: read

jobs:
  quality-gate:
    uses: PROLE-ISLAND/.github/.github/workflows/reusable-quality-gate.yml@main
    with:
      language: 'ja'
      ci_workflow_name: 'CI'
      bronze_coverage: 80
      silver_coverage: 85
      gold_coverage: 95
