# =====================================================
# ã‚»ã‚­ãƒ¥ãƒªãƒ†ã‚£ç›£æŸ»ï¼ˆçµ„ç¹”ãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆï¼‰
# ä¾å­˜è„†å¼±æ€§ã‚¹ã‚­ãƒ£ãƒ³ãƒ»ã‚·ãƒ¼ã‚¯ãƒ¬ãƒƒãƒˆæ¤œå‡º
# DoD Silver åŸºæº– C10 ã«å¯¾å¿œ
# =====================================================

name: ðŸ”’ Security Audit

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, develop]
  schedule:
    # æ¯Žé€±æœˆæ›œ 9:00 JST (0:00 UTC)
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  # ===========================================
  # ä¾å­˜è„†å¼±æ€§ã‚¹ã‚­ãƒ£ãƒ³ï¼ˆC10ï¼‰
  # ===========================================
  dependency-audit:
    name: ðŸ“¦ Dependency Audit
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Checkout
        uses: actions/checkout@v4

      - name: ðŸ“¦ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: ðŸ“¥ Install dependencies
        run: npm ci

      # npm auditï¼ˆé«˜ãƒ»é‡å¤§ã®ã¿å¤±æ•—ï¼‰
      - name: ðŸ” npm audit (high/critical)
        run: npm audit --audit-level=high
        continue-on-error: true
        id: npm-audit

      # npm audit ã®è©³ç´°ãƒ¬ãƒãƒ¼ãƒˆ
      - name: ðŸ“Š npm audit report
        run: |
          echo "## ðŸ“¦ npm audit Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          npm audit --json | jq -r '.metadata | "Total: \(.totalDependencies) deps, \(.vulnerabilities.total) vulnerabilities (\(.vulnerabilities.high) high, \(.vulnerabilities.critical) critical)"' >> $GITHUB_STEP_SUMMARY || echo "No vulnerabilities found" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
        continue-on-error: true

  # ===========================================
  # ã‚·ãƒ¼ã‚¯ãƒ¬ãƒƒãƒˆæ¤œå‡º
  # ===========================================
  secret-scan:
    name: ðŸ” Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # gitleaks ã«ã‚ˆã‚‹ã‚·ãƒ¼ã‚¯ãƒ¬ãƒƒãƒˆæ¤œå‡º
      - name: ðŸ” Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

  # ===========================================
  # CodeQL é™çš„è§£æž
  # ===========================================
  codeql:
    name: ðŸ”¬ CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: ðŸ“¥ Checkout
        uses: actions/checkout@v4

      - name: ðŸ”¬ Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript-typescript

      - name: ðŸ”¬ Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript-typescript"

  # ===========================================
  # SASTï¼ˆé™çš„ã‚¢ãƒ—ãƒªã‚±ãƒ¼ã‚·ãƒ§ãƒ³ã‚»ã‚­ãƒ¥ãƒªãƒ†ã‚£ãƒ†ã‚¹ãƒˆï¼‰
  # ===========================================
  sast:
    name: ðŸ›¡ï¸ SAST Scan
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Checkout
        uses: actions/checkout@v4

      - name: ðŸ“¦ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: ðŸ“¥ Install dependencies
        run: npm ci

      # ESLint ã‚»ã‚­ãƒ¥ãƒªãƒ†ã‚£ãƒ—ãƒ©ã‚°ã‚¤ãƒ³
      - name: ðŸ›¡ï¸ ESLint Security Check
        run: |
          # eslint-plugin-security ãŒã‚ã‚‹å ´åˆã®ã¿å®Ÿè¡Œ
          if npm list eslint-plugin-security 2>/dev/null; then
            npx eslint --plugin security --rule 'security/detect-object-injection: warn' src/ || true
          else
            echo "::notice::eslint-plugin-security not installed. Skipping."
          fi
        continue-on-error: true

  # ===========================================
  # ã‚»ã‚­ãƒ¥ãƒªãƒ†ã‚£ã‚µãƒžãƒªãƒ¼
  # ===========================================
  security-summary:
    name: ðŸ“‹ Security Summary
    runs-on: ubuntu-latest
    needs: [dependency-audit, secret-scan, codeql, sast]
    if: always()

    steps:
      - name: ðŸ“ Post Summary
        uses: actions/github-script@v7
        with:
          script: |
            const depResult = '${{ needs.dependency-audit.result }}';
            const secretResult = '${{ needs.secret-scan.result }}';
            const codeqlResult = '${{ needs.codeql.result }}';
            const sastResult = '${{ needs.sast.result }}';

            const allPassed = depResult === 'success' &&
                              secretResult === 'success' &&
                              codeqlResult === 'success' &&
                              sastResult === 'success';

            const comment = `## ðŸ”’ Security Audit Results

            | Check | Result |
            |-------|--------|
            | ðŸ“¦ Dependency Audit | ${depResult === 'success' ? 'âœ…' : 'âš ï¸'} |
            | ðŸ” Secret Scan | ${secretResult === 'success' ? 'âœ…' : 'âš ï¸'} |
            | ðŸ”¬ CodeQL | ${codeqlResult === 'success' ? 'âœ…' : 'âš ï¸'} |
            | ðŸ›¡ï¸ SAST | ${sastResult === 'success' ? 'âœ…' : 'âš ï¸'} |

            ${allPassed ? '### âœ… All security checks passed' : '### âš ï¸ Some checks need attention'}

            > DoD Silver åŸºæº– C10: ä¾å­˜è„†å¼±æ€§ã‚¹ã‚­ãƒ£ãƒ³
            `;

            console.log(comment);

            // PRã®å ´åˆã®ã¿ã‚³ãƒ¡ãƒ³ãƒˆ
            if (context.eventName === 'pull_request') {
              const { data: comments } = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
              });

              const botComment = comments.find(c =>
                c.user.type === 'Bot' && c.body.includes('Security Audit Results')
              );

              if (botComment) {
                await github.rest.issues.updateComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: botComment.id,
                  body: comment
                });
              } else {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  body: comment
                });
              }
            }
